### ISSUE TITLE
Point to OpenShift bug mentioned

### ISSUE THREAD

**Issue by apupier** [rhd-gitops-example/docs#16]
it is mentioned "Workaround a OpenShift Route bug by ". https://github.com/rhd-gitops-example/docs/blame/502f4db1de0d10737d0c890eb99111cd78b3ff3b/journey/day1/README.md#L191
it would be nice to point to the bug so that it will be easier to know when it is fixed and would allow potentially readers to vote/fix the bug in OpenShift.

**Comment by sbose78** [comment]
cc @chetan-rns

**Comment by chetan-rns** [comment]
@sbose78 @apupier This issue is already resolved. The updated docs don't mention this workaround. This is fixed in ArgoCD as well https://github.com/argoproj/argo-cd/pull/3754

**Comment by chetan-rns** [comment]
Closing this issue since it's resolved
